###
# First Stage 1: Install Ruby & POSIX Dependencies

# Make sure it matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=3.2.0
FROM ruby:$RUBY_VERSION

ENV DEBIAN_FRONTEND=noninteractive

# Install JavaScript dependencies and libvips for Active Storage
ARG NODE_LTS_VERSION=18
RUN curl -sL https://deb.nodesource.com/setup_${NODE_LTS_VERSION}.x | bash \
    && apt-get update -qq \
    && apt-get install -y \
    build-essential \
    libpq-dev \
    libvips \
    nodejs \
    && npm install -g yarn

# Install Google Chrome
RUN curl -sL https://dl.google.com/linux/linux_signing_key.pub > /etc/apt/trusted.gpg.d/google_linux_signing_key.asc \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | tee /etc/apt/sources.list.d/google_chrome.list \
    && apt-get update -qq \
    && apt-get install -y \
    google-chrome-stable \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

WORKDIR /app

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle install \
    --retry 3 \
    --jobs 4

COPY . /app

RUN yarn install
