version: '3'
services:
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    tmpfs:
      - /tmp

  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - rails_cache:/app/tmp/cache
    environment:
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: 'true'
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/bonne_bouche_development
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:13.9
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 54320:5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  web:
    <<: *backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails -s -b '0.0.0.0'"
    ports:
      - 3000:3000

  js:
    <<: *backend
    command: bash -c "yarn build --watch"

  css:
    <<: *backend
    command: bash -c "yarn build:css --watch"

volumes:
  bundle:
  node_modules:
  packs:
  postgres:
  rails_cache:
